#!/usr/bin/env python3
"""Emit the rollout-budget and sliding-plan tables from arm_sweep results.csv.

Both are pooled over three planner seeds at the ridge cell (weight 8192000,
margin 0.01), so a row is comparable to the corresponding cell of the landscape
table. Per-seed counts and confidence intervals stay in the appendix; these
tables carry only what the surrounding argument uses.

Usage:
  make_rollout_table.py --d1 <dir> --a3 <dir> --annealed <dir>
                        --out-rollouts rollout_table.tex
                        --out-sliding sliding_table.tex
                        [--out-seeds seed_table.tex]
"""
import argparse
import csv
import math
import os
from collections import defaultdict


def load(path):
    """arm -> (solved, trials, collided, [per-seed solved], mean ms/iter)."""
    if not path:
        return {}
    f = os.path.join(path, "results.csv")
    if not os.path.exists(f):
        return {}
    agg = defaultdict(lambda: [0, 0, 0, [], []])
    for r in csv.DictReader(open(f)):
        a = agg[r["arm"]]
        a[0] += int(r["solved"])
        a[1] += int(r["trials"])
        a[2] += int(r["collided"])
        a[3].append(int(r["solved"]))
        a[4].append(float(r["ms_per_iter_contended"]))
    return {k: (v[0], v[1], v[2], v[3], sum(v[4]) / len(v[4])) for k, v in agg.items()}


def wilson(k, n, z=1.96):
    if n == 0:
        return (0.0, 0.0)
    p, d = k / n, 1 + z * z / n
    c = (p + z * z / (2 * n)) / d
    h = z * math.sqrt(p * (1 - p) / n + z * z / (4 * n * n)) / d
    return (100 * (c - h), 100 * (c + h))


def ztest(k1, n1, k2, n2):
    if not (n1 and n2):
        return (0.0, 0.0, 1.0)
    p1, p2 = k1 / n1, k2 / n2
    p = (k1 + k2) / (n1 + n2)
    se = math.sqrt(p * (1 - p) * (1 / n1 + 1 / n2))
    if se == 0:
        return (100 * (p2 - p1), 0.0, 1.0)
    z = (p2 - p1) / se
    return (100 * (p2 - p1), z, math.erfc(abs(z) / math.sqrt(2)))


def fmt_p(p):
    return "$<0.001$" if p < 0.001 else f"${p:.3f}$"


# (label, arm key, source, trajectories, rollout multiplier)
BUDGET_ROWS = [
    ("Predictive", "nt10", "d1", 10, 1),
    ("Predictive", "nt20", "d1", 20, 1),
    ("Predictive", "nt40", "d1", 40, 1),
    ("Predictive", "nt80", "d1", 80, 1),
    ("Annealed", "as_nt10", "ann", 10, 4),
    ("Annealed", "as_nt40", "ann", 40, 4),
]


def rollout_table(d1, ann, out):
    """Rollout budget per planning iteration, both planners, one table.

    Annealed sampling draws its trajectories once per annealing iteration and
    runs four, so its rollout budget is 4x its trajectory count. Listing both
    planners against the rollouts column rather than the trajectory column is
    the point: every earlier table in the paper compared them at trajectory
    parity, which is a 4x budget difference.
    """
    src = {"d1": d1, "ann": ann}
    rows, best = [], None
    for name, key, which, traj, mult in BUDGET_ROWS:
        rec = src[which].get(key)
        if not rec:
            continue
        k, n, c, _, ms = rec
        rate = 100 * k / n
        if best is None or rate > best:
            best = rate
        rows.append((name, traj, traj * mult, rate, 100 * c / n, ms))
    body = []
    prev = None
    for name, traj, budget, rate, col, ms in rows:
        if prev is not None and name != prev:
            body.append("\\midrule")
        prev = name
        r = f"\\textbf{{{rate:.1f}}}" if rate == best else f"{rate:.1f}"
        body.append(f"{name} & {traj} & {budget} & {r} & {col:.1f} & {ms:.2f} \\\\")
    with open(out, "w") as fh:
        fh.write(
            "% generated by make_rollout_table.py -- do not edit\n"
            "\\begin{table}[t]\n"
            "\\caption{Rollout budget per planning iteration. Annealed sampling\n"
            "runs four annealing iterations, so its budget is $4\\times$ its\n"
            "trajectory count. 150 trials per row; ms/iter is contended.}\n"
            "\\label{tab:rollouts}\n"
            "\\centering\n"
            "\\footnotesize\n"
            "\\setlength{\\tabcolsep}{4.5pt}\n"
            "\\begin{tabular}{@{}llrrrr@{}}\n"
            "\\toprule\n"
            "planner & traj. & rollouts & solved \\% & collided \\% "
            "& ms/iter \\\\\n"
            "\\midrule\n" + "\n".join(body) + "\n"
            "\\bottomrule\n"
            "\\end{tabular}\n"
            "\\end{table}\n"
        )


def seed_table(d1, ann, a3, out):
    """Appendix: per-seed counts and intervals behind the two pooled tables."""
    rows = []
    src = {"d1": d1, "ann": ann}
    for name, key, which, traj, mult in BUDGET_ROWS:
        rec = src[which].get(key)
        if not rec:
            continue
        k, n, _, seeds, _ = rec
        lo, hi = wilson(k, n)
        rows.append(
            f"{name[:4]}. & {traj} & {traj*mult} & {k}/{n} & "
            f"{'/'.join(map(str, seeds))} & [{lo:.1f}, {hi:.1f}] \\\\"
        )
    for key, label in [
        ("slide0_w8192k_m001", "off & $8.19$M/$.01$"),
        ("slide1_w8192k_m001", "on & $8.19$M/$.01$"),
        ("slide0_w2048k_m002", "off & $2.05$M/$.02$"),
        ("slide1_w2048k_m002", "on & $2.05$M/$.02$"),
        ("slide0_w2048k_m001", "off & $2.05$M/$.01$"),
        ("slide1_w2048k_m001", "on & $2.05$M/$.01$"),
    ]:
        rec = a3.get(key)
        if not rec:
            continue
        k, n, _, seeds, _ = rec
        lo, hi = wilson(k, n)
        rows.append(
            f"{label} & {k}/{n} & {'/'.join(map(str, seeds))} & "
            f"[{lo:.1f}, {hi:.1f}] \\\\"
        )
    with open(out, "w") as fh:
        fh.write(
            "% generated by make_rollout_table.py -- do not edit\n"
            "\\begin{table}[t]\n"
            "\\caption{Per-seed counts behind Tables~\\ref{tab:rollouts} and\n"
            "\\ref{tab:sliding}. Upper block is the rollout budget, lower the\n"
            "sliding plan; each seed is 50 trials.}\n"
            "\\label{tab:seeds}\n"
            "\\centering\n"
            "\\footnotesize\n"
            "\\setlength{\\tabcolsep}{4pt}\n"
            "\\begin{tabular}{@{}llrrlc@{}}\n"
            "\\toprule\n"
            "& & & solved & per seed & 95\\% CI \\\\\n"
            "\\midrule\n" + "\n".join(rows[:6]) + "\n\\midrule\n"
            + "\n".join(rows[6:]) + "\n"
            "\\bottomrule\n"
            "\\end{tabular}\n"
            "\\end{table}\n"
        )


def sliding_table(a3, out):
    """Sliding plan on/off at the three best ridge cells, paired within a cell."""
    cells = [
        ("w8192k_m001", "$8.19\\times10^{6}$ & $0.01$"),
        ("w2048k_m002", "$2.05\\times10^{6}$ & $0.02$"),
        ("w2048k_m001", "$2.05\\times10^{6}$ & $0.01$"),
    ]
    rows = []
    t0 = t1 = n0 = n1 = 0
    for key, label in cells:
        off, on = a3.get("slide0_" + key), a3.get("slide1_" + key)
        if not (off and on):
            continue
        t0 += off[0]; n0 += off[1]; t1 += on[0]; n1 += on[1]
        d, _, p = ztest(off[0], off[1], on[0], on[1])
        rows.append(
            f"{label} & {100*off[0]/off[1]:.1f} & {100*off[2]/off[1]:.1f} & "
            f"{100*on[0]/on[1]:.1f} & {100*on[2]/on[1]:.1f} & "
            f"${d:+.1f}$ & {fmt_p(p)} \\\\"
        )
    d, _, p = ztest(t0, n0, t1, n1)
    pooled = (
        f"\\midrule\n\\multicolumn{{2}}{{@{{}}l}}{{pooled}} & {100*t0/n0:.1f} & "
        f"& {100*t1/n1:.1f} & & ${d:+.1f}$ & {fmt_p(p)} \\\\"
    )
    with open(out, "w") as fh:
        fh.write(
            "% generated by make_rollout_table.py -- do not edit\n"
            "\\begin{table}[t]\n"
            "\\caption{Sliding plan off against on, three ridge cells, 150 trials\n"
            "per arm. ``col'' is the collision rate. Off is the default.}\n"
            "\\label{tab:sliding}\n"
            "\\centering\n"
            "\\footnotesize\n"
            "\\setlength{\\tabcolsep}{4pt}\n"
            "\\begin{tabular}{@{}rrrrrrrr@{}}\n"
            "\\toprule\n"
            "& & \\multicolumn{2}{c}{off} & \\multicolumn{2}{c}{on} & & \\\\\n"
            "\\cmidrule(lr){3-4}\\cmidrule(lr){5-6}\n"
            "$w_{\\mathrm{avoid}}$ & $\\delta$ & \\% & col & \\% & col "
            "& $\\Delta$ & $p$ \\\\\n"
            "\\midrule\n" + "\n".join(rows) + "\n" + pooled + "\n"
            "\\bottomrule\n"
            "\\end{tabular}\n"
            "\\end{table}\n"
        )


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--d1", required=True)
    ap.add_argument("--a3", required=True)
    ap.add_argument("--annealed", default="")
    ap.add_argument("--out-rollouts", required=True)
    ap.add_argument("--out-sliding", required=True)
    ap.add_argument("--out-seeds", default="")
    a = ap.parse_args()
    d1, ann, a3 = load(a.d1), load(a.annealed), load(a.a3)
    rollout_table(d1, ann, a.out_rollouts)
    sliding_table(a3, a.out_sliding)
    if a.out_seeds:
        seed_table(d1, ann, a3, a.out_seeds)
    print("wrote", a.out_rollouts, a.out_sliding, a.out_seeds)


if __name__ == "__main__":
    main()
