#!/usr/bin/env python3
"""Emit the rollout-count and sliding-plan tables from arm_sweep results.csv.

Both tables are pooled over the three planner seeds, and both are anchored at
the same ridge cell (weight 8192000, margin 0.01), so a row here is comparable
to the corresponding cell of Table~\\ref{tab:landscape}.

Usage:
  make_rollout_table.py --d1 <dir> --a3 <dir> [--as <dir>] [--ps160 <dir>]
                        --out-rollouts rollout_table.tex
                        --out-sliding sliding_table.tex
"""
import argparse
import csv
import math
import os
from collections import defaultdict


def load(path):
    """arm -> (solved, trials, collided, [per-seed solved], mean ms/iter)."""
    if not path:
        return {}
    f = os.path.join(path, "results.csv")
    if not os.path.exists(f):
        return {}
    agg = defaultdict(lambda: [0, 0, 0, [], []])
    for r in csv.DictReader(open(f)):
        a = agg[r["arm"]]
        a[0] += int(r["solved"])
        a[1] += int(r["trials"])
        a[2] += int(r["collided"])
        a[3].append(int(r["solved"]))
        a[4].append(float(r["ms_per_iter_contended"]))
    return {k: (v[0], v[1], v[2], v[3], sum(v[4]) / len(v[4])) for k, v in agg.items()}


def wilson(k, n, z=1.96):
    if n == 0:
        return (0.0, 0.0)
    p, d = k / n, 1 + z * z / n
    c = (p + z * z / (2 * n)) / d
    h = z * math.sqrt(p * (1 - p) / n + z * z / (4 * n * n)) / d
    return (100 * (c - h), 100 * (c + h))


def ztest(k1, n1, k2, n2):
    """Two-proportion z on arm2 minus arm1. Returns (delta_pts, z, p)."""
    if not (n1 and n2):
        return (0.0, 0.0, 1.0)
    p1, p2 = k1 / n1, k2 / n2
    p = (k1 + k2) / (n1 + n2)
    se = math.sqrt(p * (1 - p) * (1 / n1 + 1 / n2))
    if se == 0:
        return (100 * (p2 - p1), 0.0, 1.0)
    z = (p2 - p1) / se
    return (100 * (p2 - p1), z, math.erfc(abs(z) / math.sqrt(2)))


def fmt_p(p):
    return "$<0.001$" if p < 0.001 else f"${p:.3f}$"


def rollout_table(d1, ps160, out):
    """Rollouts per planning iteration, predictive sampling, at the ridge cell.

    The baseline row is nt10, which is also the w8192000/delta0.01 cell of the
    landscape grid; agreement between the two is the check that the rebuilt
    binary is neutral.
    """
    arms = [("nt10", "10"), ("nt20", "20"), ("nt40", "40"), ("nt80", "80")]
    src = dict(d1)
    if ps160:
        src.update(ps160)
        if "nt160" in ps160:
            arms.append(("nt160", "160"))
    base = src.get("nt10")
    rows = []
    for key, label in arms:
        if key not in src:
            continue
        k, n, c, seeds, ms = src[key]
        lo, hi = wilson(k, n)
        d, z, p = ztest(base[0], base[1], k, n)
        cmp_ = "---" if key == "nt10" else f"${d:+.1f}$ & {fmt_p(p)}"
        if key == "nt10":
            cmp_ = "--- & ---"
        rows.append(
            f"{label} & {k}/{n} & {100*k/n:.1f} & [{lo:.1f}, {hi:.1f}] & "
            f"{'/'.join(str(s) for s in seeds)} & {cmp_} \\\\"
        )
    with open(out, "w") as fh:
        fh.write(
            "% generated by make_rollout_table.py -- do not edit\n"
            "\\begin{table}[t]\n"
            "\\caption{Rollouts per planning iteration, predictive sampling at the\n"
            "ridge cell $w_{\\mathrm{avoid}} = 8.19\\times10^{6}$, $\\delta = 0.01$~m.\n"
            "Iterations per control step are fixed at four for every row, so this\n"
            "varies the breadth of each decision, not the number of decisions.\n"
            "$\\Delta$ and $p$ are against the 10-rollout row.}\n"
            "\\label{tab:rollouts}\n"
            "\\centering\n"
            "\\footnotesize\n"
            "\\setlength{\\tabcolsep}{4pt}\n"
            "\\begin{tabular}{@{}lrrcrrr@{}}\n"
            "\\toprule\n"
            "rollouts & solved & \\% & 95\\% CI & per seed & $\\Delta$ & $p$ \\\\\n"
            "\\midrule\n" + "\n".join(rows) + "\n"
            "\\bottomrule\n"
            "\\end{tabular}\n"
            "\\end{table}\n"
        )


def sliding_table(a3, out):
    """Sliding plan on/off at the three best ridge cells, paired within a cell."""
    cells = [
        ("w8192k_m001", "$8.19\\times10^{6}$ & $0.01$"),
        ("w2048k_m002", "$2.05\\times10^{6}$ & $0.02$"),
        ("w2048k_m001", "$2.05\\times10^{6}$ & $0.01$"),
    ]
    rows = []
    t0 = t1 = n0 = n1 = 0
    for key, label in cells:
        off = a3.get("slide0_" + key)
        on = a3.get("slide1_" + key)
        if not (off and on):
            continue
        t0 += off[0]; n0 += off[1]; t1 += on[0]; n1 += on[1]
        d, z, p = ztest(off[0], off[1], on[0], on[1])
        rows.append(
            f"{label} & {100*off[0]/off[1]:.1f} & {100*off[2]/off[1]:.1f} & "
            f"{100*on[0]/on[1]:.1f} & {100*on[2]/on[1]:.1f} & "
            f"${d:+.1f}$ & {fmt_p(p)} \\\\"
        )
    d, z, p = ztest(t0, n0, t1, n1)
    pooled = (
        f"\\midrule\n\\multicolumn{{2}}{{@{{}}l}}{{pooled}} & {100*t0/n0:.1f} & "
        f"& {100*t1/n1:.1f} & & ${d:+.1f}$ & {fmt_p(p)} \\\\"
    )
    with open(out, "w") as fh:
        fh.write(
            "% generated by make_rollout_table.py -- do not edit\n"
            "\\begin{table}[t]\n"
            "\\caption{Sliding plan off against on, at the three best cells of the\n"
            "ridge, 150 trials per arm per cell. ``col'' is the collision rate.\n"
            "Off is the default and is what every other table in this paper uses.}\n"
            "\\label{tab:sliding}\n"
            "\\centering\n"
            "\\footnotesize\n"
            "\\setlength{\\tabcolsep}{4pt}\n"
            "\\begin{tabular}{@{}rrrrrrrr@{}}\n"
            "\\toprule\n"
            "& & \\multicolumn{2}{c}{off} & \\multicolumn{2}{c}{on} & & \\\\\n"
            "\\cmidrule(lr){3-4}\\cmidrule(lr){5-6}\n"
            "$w_{\\mathrm{avoid}}$ & $\\delta$ & \\% & col & \\% & col "
            "& $\\Delta$ & $p$ \\\\\n"
            "\\midrule\n" + "\n".join(rows) + "\n" + pooled + "\n"
            "\\bottomrule\n"
            "\\end{tabular}\n"
            "\\end{table}\n"
        )


def budget_table(d1, ann, out):
    """Predictive against annealed sampling at matched rollouts per iteration.

    Annealed sampling draws `num_trajectory` rollouts on each of its four
    annealing iterations, so its rollout budget is 4x its trajectory count.
    Lining the two planners up by rollouts rather than by trajectories is the
    whole point of the table: every previous comparison in this paper gave
    annealed sampling 4x the samples without saying so.
    """
    rows = [
        ("Predictive", "10", 1, d1.get("nt10")),
        ("Predictive", "40", 1, d1.get("nt40")),
        ("Predictive", "80", 1, d1.get("nt80")),
        ("Annealed", "10", 4, ann.get("as_nt10")),
        ("Annealed", "40", 4, ann.get("as_nt40")),
    ]
    out_rows = []
    for name, traj, mult, rec in rows:
        if not rec:
            continue
        k, n, c, seeds, ms = rec
        budget = int(traj) * mult
        out_rows.append(
            f"{name} & {traj} & {budget} & {100*k/n:.1f} & {100*c/n:.1f} & "
            f"{ms:.2f} \\\\"
        )
    with open(out, "w") as fh:
        fh.write(
            "% generated by make_rollout_table.py -- do not edit\n"
            "\\begin{table}[t]\n"
            "\\caption{Predictive against annealed sampling at matched rollout\n"
            "budgets, same ridge cell, 150 trials per row. Annealed sampling draws\n"
            "its trajectories once per annealing iteration and runs four, so its\n"
            "budget is $4\\times$ its trajectory count. ms/iter is contended\n"
            "(five concurrent jobs) and is comparable within this table only.}\n"
            "\\label{tab:budget}\n"
            "\\centering\n"
            "\\footnotesize\n"
            "\\setlength{\\tabcolsep}{4pt}\n"
            "\\begin{tabular}{@{}llrrrr@{}}\n"
            "\\toprule\n"
            "planner & traj. & rollouts/iter & solved \\% & collided \\% "
            "& ms/iter \\\\\n"
            "\\midrule\n" + "\n".join(out_rows) + "\n"
            "\\bottomrule\n"
            "\\end{tabular}\n"
            "\\end{table}\n"
        )


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--d1", required=True)
    ap.add_argument("--a3", required=True)
    ap.add_argument("--annealed", default="")
    ap.add_argument("--ps160", default="")
    ap.add_argument("--out-rollouts", required=True)
    ap.add_argument("--out-sliding", required=True)
    ap.add_argument("--out-budget", default="")
    a = ap.parse_args()
    rollout_table(load(a.d1), load(a.ps160), a.out_rollouts)
    sliding_table(load(a.a3), a.out_sliding)
    if a.out_budget:
        budget_table(load(a.d1), load(a.annealed), a.out_budget)
    print("wrote", a.out_rollouts, a.out_sliding, a.out_budget)


if __name__ == "__main__":
    main()
